### ISSUE TITLE
Is gcexport currently working I am receiving an HTTP 404 error

### ISSUE THREAD

**Issue by rsjrny** [JohannesHeinrich/garmin-connect-export#1]
I know garmin has made many changes over the years to their web pages and I am receiving a 404 error. 

Microsoft Windows [Version 10.0.16299.309]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Program Files (x86)>cd python27

C:\Program Files (x86)\Python27>python C:/users/russ/dropbox/garminconnectexports/gcexport.py -d C:/users/russ/dropbox/garminconnectexports/Russ/ -c "5" -f original -u --username "xxxx" --password "xxxxxxxxxxx"
Welcome to Garmin Connect Exporter!
Warning: Output directory already exists. Already downloaded files will be skipped.
Traceback (most recent call last):
  File "C:/users/russ/dropbox/garminconnectexports/gcexport.py", line 99, in <module>
    hostname_url = http_req('http://connect.garmin.com/gauth/hostname')
  File "C:/users/russ/dropbox/garminconnectexports/gcexport.py", line 78, in http_req
    response = opener.open(request, data=post)  # This line may throw a urllib2.HTTPError.
  File "C:\Program Files (x86)\Python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "C:\Program Files (x86)\Python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Program Files (x86)\Python27\lib\urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "C:\Program Files (x86)\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Program Files (x86)\Python27\lib\urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Program Files (x86)\Python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "C:\Program Files (x86)\Python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Program Files (x86)\Python27\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "C:\Program Files (x86)\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Program Files (x86)\Python27\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found

C:\Program Files (x86)\Python27>

**Comment by AngelaKru** [comment]
Garmin seems to have deprecated their legacy api

Use these instead, works for me on a similar script:
REDIRECT = "https://connect.garmin.com/modern/"
BASE_URL = "https://sso.garmin.com/sso/login"
GAUTH = "https://connect.garmin.com/modern/auth/hostname"
SSO = "https://sso.garmin.com/sso"
CSS = "https://static.garmincdn.com/com.garmin.connect/ui/css/gauth-custom-v1.2-min.css"

Activity service and downloads all use the 'modern' api too:
ACTIVITIES = "https://connect.garmin.com/modern/proxy/activitylist-service/activities/search/activities?start=%s&limit=%s"
WELLNESS = "https://connect.garmin.com/modern/proxy/userstats-service/wellness/daily/%s?fromDate=%s&untilDate=%s"
DAILYSUMMARY = "https://connect.garmin.com/modern/proxy/wellness-service/wellness/dailySummaryChart/%s?date=%s"

TCX = "https://connect.garmin.com/modern/proxy/download-service/export/tcx/activity/%s"
GPX = "https://connect.garmin.com/modern/proxy/download-service/export/gpx/activity/%s"

**Comment by AngelaKru** [comment]
Oh and the format of the json result from activity service has changed: no longer an array of activities with a summary, now its a simple list of json activites, so you'll need to change your ['activity']['activityId'] to ['activityId'] etc

**Comment by rsjrny** [comment]
I found the fix in the GCExport repository by PE-st
